### ISSUE TITLE
Problem about video frames

### ISSUE THREAD

**Issue by aopolin-lv** [Buzz-Beater/EgoTaskQA#4]
Hello, authors. I am excited about seeing this work.
When trying to replement the training process of VisualBert, I met a problem in the dataset init period.

In the ```load_frame_paths_from_interval``` function of line 31 in ```dataset.py```, it uses the ```video_path```, ```start_frame```, ```end_frame``` variable. However, the given data does not provide video frames.
```
    def load_frame_paths_from_interval(self, interval):
        video_name, fpv, start, end = interval.split('|') # # [start, end)
        start, end = int(start) + 1 , int(end) + 1 # # 
        start, end = str(start), str(end)
        start, end = start.rjust(5, '0'), end.rjust(5, '0')
        video_path = os.path.join('/scratch/generalvision/LEMMA/videos', video_name, f'fpv{fpv[-1]}', 'img_*.jpg')
        all_video_frames = sorted(glob.glob(video_path))
        start_frame = os.path.join('/scratch/generalvision/LEMMA/videos', video_name, f'fpv{fpv[-1]}', f'img_{start}.jpg')
        end_frame = os.path.join('/scratch/generalvision/LEMMA/videos', video_name, f'fpv{fpv[-1]}', f'img_{end}.jpg')
        start_idx = all_video_frames.index(start_frame)
        end_idx = all_video_frames.index(end_frame)
        return all_video_frames[start_idx:end_idx]
```

Question:
1. What does the fpv mean?
2. How can I get the video frames? Could you provide a link for downloading or what sampling rate should I use to extract frames for the raw videos?
3. What is the meaning of ```ori```, ```vis0```, ```vis1``` in the provided ```MODEL``` folder?

**Comment by Buzz-Beater** [comment]
Hi, thanks for the interest. First of all, for the videos, you can download the original video frames with the link provided [here](https://sites.google.com/view/lemma-activity). The ```fpv``` indicates first person view, the meaning of ```ori```, ```vis0```, and ```vis1``` corresponds to the different level of clarity in actions when used in questions, it matches the experiment discussion in Fig.4 of the original paper.

**Comment by yangayang617** [comment]
Excuse me, may I ask how to solve the problem of not being able to find this file in features?
this：
download (gdrive) features/glove.840.300d.pkl to $GLOVE_PT_PATH.
I cannot find glove.840.300d.pkl
